Repository edamontology/edamontology, pull requests merged in 2024-09, with the labels that each got.

#883 Merging DM concepts etc. from WebProtégé
  EDAM_dev.owl
Labels: concept/term addition, done - staged for release, done in WebProtégé, merge 1st

#884 Replaced tab characters
  EDAM_dev.owl
Labels: polishing, manual merge needed, merge 2nd

#772 Added synonym & related terms for DM
  EDAM_dev.owl
Labels: concept/term addition, manual merge needed, merge 2nd

#699 changed http to https
  README.md
Labels: documentation, merge anytime

#893 Updated templates for concepts (in CONTRIBUTING.md)
  CONTRIBUTING.md
Labels: documentation, polishing, high priority, merge anytime

#895 new version upload artifact
  .github/workflows/caseologue.yml
Labels: bug, validation

#899 Added some OWL ontology annotation properties: versionIRI, versionInfo, priorVersion
  EDAM_dev.owl
  releases/EDAM.owl
  releases/EDAM_1.25.owl
Labels: enhancement, polishing, partially fixed, access | publication | release, high priority, merge anytime

#888 Add QC and MS QC operations
  EDAM_dev.owl
Labels: question, concept/term addition, broad conceptual issue, high priority
